services:
    paper-monitor:
        environment:
            - PAPER_MONITOR_STORAGE_ROOT=/data/uploads
            - PAPER_MONITOR_GIT_ROOT=/data/git-remotes
            - PAPER_MONITOR_BASE_URL=http://localhost:8080
            - PAPER_MONITOR_TTS_BASE_URL=http://paper-monitor-piper-api:8090
            - QUARKUS_DATASOURCE_JDBC_URL=jdbc:sqlite:/data/paper-monitor.db?busy_timeout=5000
        ports:
            - 8080:8080
        volumes:
            - ./app/data:/data:rw
        image: docker.io/nherbaut/paper-monitor:1.0.0-SNAPSHOT
    paper-monitor-piper-api:
        ports:
            - 8090:8090
        environment:
            - PIPER_BIN=/usr/local/bin/piper
        volumes:
            - /home/nherbaut/.local/piper/models/:/models:ro
        image: docker.io/nherbaut/paper-monitor-piper-api:latest
