quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:paper-monitor.db?busy_timeout=5000
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=false
quarkus.qute.content-types.html=text/html
quarkus.http.limits.max-body-size=50M
paper-monitor.poller.every=60s
paper-monitor.storage.root=uploads
