quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=false
quarkus.qute.content-types.html=text/html
quarkus.http.limits.max-body-size=50M
quarkus.http.limits.max-form-attribute-size=1M
%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.db-name=paper_monitor
%dev.quarkus.datasource.devservices.username=paper_monitor
%dev.quarkus.datasource.devservices.password=paper_monitor
%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.db-name=paper_monitor_test
%test.quarkus.datasource.devservices.username=paper_monitor
%test.quarkus.datasource.devservices.password=paper_monitor
%prod.quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}
%prod.quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
%prod.quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}
paper-monitor.poller.every=60s
paper-monitor.storage.root=../data/uploads
paper-monitor.git.root=../data/git-remotes
paper-monitor.base-url=http://localhost:8080
paper-monitor.tts.base-url=http://localhost:8090
paper-monitor.tts.default-voice=en_US-lessac-medium
quarkus.container-image.build=true
quarkus.container-image.builder=docker
quarkus.docker.dockerfile-jvm-path=src/main/docker/Dockerfile.jvm
