quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:../data/paper-monitor.db?busy_timeout=5000
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=false
quarkus.qute.content-types.html=text/html
quarkus.http.limits.max-body-size=50M
quarkus.http.limits.max-form-attribute-size=1M
paper-monitor.poller.every=60s
paper-monitor.storage.root=../data/uploads
paper-monitor.git.root=../data/git-remotes
paper-monitor.base-url=http://localhost:8080
paper-monitor.tts.base-url=http://localhost:8090
paper-monitor.tts.default-voice=en_US-lessac-medium
quarkus.container-image.build=true
quarkus.container-image.builder=docker
quarkus.docker.dockerfile-jvm-path=src/main/docker/Dockerfile.jvm
